# syntax=docker/dockerfile:1

ARG UPSTREAM_IMAGE=ghcr.io/open-webui/open-webui:main

FROM --platform=$BUILDPLATFORM node:22-alpine3.20 AS build
ARG BUILD_HASH=dev-build

WORKDIR /app

RUN apk add --no-cache git

COPY package.json package-lock.json ./
RUN npm ci --force

COPY . .
ENV APP_BUILD_HASH=${BUILD_HASH}
RUN npm run build

FROM ${UPSTREAM_IMAGE}
ARG BUILD_HASH=dev-build

COPY --from=build /app/build /app/build
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/CHANGELOG.md /app/CHANGELOG.md

ENV WEBUI_BUILD_VERSION=${BUILD_HASH}
